version: 2

updates:
  - package-ecosystem: npm
    directory: /fynancials-client-angular
    schedule:
      interval: weekly
      day: saturday
      time: "06:00"
      timezone: "Europe/Berlin"
    cooldown:
      default-days: 7
    groups:
      client-security-updates:
        applies-to: security-updates
        patterns: [ "*" ]
      client-version-updates:
        applies-to: version-updates
        patterns: [ "*" ]
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: npm
    directory: /fynancials-api
    schedule:
      interval: weekly
      day: saturday
      time: "06:00"
      timezone: "Europe/Berlin"
    cooldown:
      default-days: 7
    groups:
      api-security-updates:
        applies-to: security-updates
        patterns: [ "*" ]
      api-version-updates:
        applies-to: version-updates
        patterns: [ "*" ]
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: maven
    directory: /fynancials-server-spring
    schedule:
      interval: weekly
      day: saturday
      time: "06:00"
      timezone: "Europe/Berlin"
    cooldown:
      default-days: 7
    groups:
      server-security-updates:
        applies-to: security-updates
        patterns: [ "*" ]
      server-version-updates:
        applies-to: version-updates
        patterns: [ "*" ]
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: saturday
      time: "06:00"
      timezone: "Europe/Berlin"
