DELETE FROM CLIENT_CONFIGURATION;
ALTER TABLE CLIENT_CONFIGURATION ALTER COLUMN ID RESTART WITH 1;

DELETE FROM SERVER_CONFIGURATION;
ALTER TABLE SERVER_CONFIGURATION ALTER COLUMN ID RESTART WITH 1;

DELETE FROM SECURITY_GROUP;
ALTER TABLE SECURITY_GROUP ALTER COLUMN ID RESTART WITH 1;

DELETE FROM DIVIDEND_ANNOUNCEMENT;
ALTER TABLE DIVIDEND_ANNOUNCEMENT ALTER COLUMN ID RESTART WITH 1;

DELETE FROM DIVIDEND_ANNOUNCEMENT_CONFIG;

DELETE FROM DIVIDEND_ANNOUNCEMENT_DATA_SOURCE;
ALTER TABLE DIVIDEND_ANNOUNCEMENT_DATA_SOURCE ALTER COLUMN ID RESTART WITH 101;

DELETE FROM TRANSACTION;
ALTER TABLE TRANSACTION ALTER COLUMN ID RESTART WITH 1;

DELETE FROM DEPOT;
ALTER TABLE DEPOT ALTER COLUMN ID RESTART WITH 1;

DELETE FROM EXCHANGE_RATE;
ALTER TABLE EXCHANGE_RATE ALTER COLUMN ID RESTART WITH 1;

DELETE FROM HISTORICAL_SECURITY_PRICE;
ALTER TABLE HISTORICAL_SECURITY_PRICE ALTER COLUMN ID RESTART WITH 1;

DELETE FROM HISTORICAL_SECURITY_PRICE_CONFIG;
ALTER TABLE HISTORICAL_SECURITY_PRICE_CONFIG ALTER COLUMN ID RESTART WITH 1;

DELETE FROM SECURITY_SYMBOL;

DELETE FROM STOCK_SPLIT;
ALTER TABLE STOCK_SPLIT ALTER COLUMN ID RESTART WITH 1;

DELETE FROM SECURITY;
ALTER TABLE SECURITY ALTER COLUMN ID RESTART WITH 1;

DELETE FROM HISTORICAL_SECURITY_PRICE_DATA_SOURCE;
ALTER TABLE HISTORICAL_SECURITY_PRICE_DATA_SOURCE ALTER COLUMN ID RESTART WITH 101;
