-- Amazon
INSERT INTO HISTORICAL_SECURITY_PRICE (SECURITY_ID, PRICE, CURRENCY, DATE, CREATED_AT, UPDATED_AT)
VALUES ((SELECT ID FROM SECURITY WHERE NAME = 'Amazon'), 134.74, 'EUR', '2023-12-01', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ((SELECT ID FROM SECURITY WHERE NAME = 'Amazon'), 133.32, 'EUR', '2023-12-04', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ((SELECT ID FROM SECURITY WHERE NAME = 'Amazon'), 136.0, 'EUR', '2023-12-05' , CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ((SELECT ID FROM SECURITY WHERE NAME = 'Amazon'), 134.68, 'EUR', '2023-12-06', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ((SELECT ID FROM SECURITY WHERE NAME = 'Amazon'), 136.28, 'EUR', '2023-12-07', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ((SELECT ID FROM SECURITY WHERE NAME = 'Amazon'), 136.5, 'EUR', '2023-12-08', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ((SELECT ID FROM SECURITY WHERE NAME = 'Amazon'), 134.62, 'EUR', '2023-12-11', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ((SELECT ID FROM SECURITY WHERE NAME = 'Amazon'), 135.5, 'EUR', '2023-12-12', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ((SELECT ID FROM SECURITY WHERE NAME = 'Amazon'), 136.88, 'EUR', '2023-12-13', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ((SELECT ID FROM SECURITY WHERE NAME = 'Amazon'), 134.54, 'EUR', '2023-12-14', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ((SELECT ID FROM SECURITY WHERE NAME = 'Amazon'), 136.66, 'EUR', '2023-12-15', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ((SELECT ID FROM SECURITY WHERE NAME = 'Amazon'), 140.04, 'EUR', '2023-12-18', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ((SELECT ID FROM SECURITY WHERE NAME = 'Amazon'), 140.04, 'EUR', '2023-12-19', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ((SELECT ID FROM SECURITY WHERE NAME = 'Amazon'), 140.94, 'EUR', '2023-12-20', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ((SELECT ID FROM SECURITY WHERE NAME = 'Amazon'), 139.2, 'EUR', '2023-12-21', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ((SELECT ID FROM SECURITY WHERE NAME = 'Amazon'), 139.26, 'EUR', '2023-12-22', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ((SELECT ID FROM SECURITY WHERE NAME = 'Amazon'), 138.22, 'EUR', '2023-12-27', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ((SELECT ID FROM SECURITY WHERE NAME = 'Amazon'), 138.34, 'EUR', '2023-12-28', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ((SELECT ID FROM SECURITY WHERE NAME = 'Amazon'), 138.58, 'EUR', '2023-12-29', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Pinterest
INSERT INTO HISTORICAL_SECURITY_PRICE (SECURITY_ID, PRICE, CURRENCY, DATE, CREATED_AT, UPDATED_AT)
VALUES ((SELECT ID FROM SECURITY WHERE NAME = 'Pinterest'), 34.79, 'USD', '2023-12-01', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ((SELECT ID FROM SECURITY WHERE NAME = 'Pinterest'), 34.5, 'USD', '2023-12-04', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ((SELECT ID FROM SECURITY WHERE NAME = 'Pinterest'), 33.52, 'USD', '2023-12-06', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ((SELECT ID FROM SECURITY WHERE NAME = 'Pinterest'), 34.02, 'USD', '2023-12-07', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ((SELECT ID FROM SECURITY WHERE NAME = 'Pinterest'), 34.91, 'USD', '2023-12-08', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ((SELECT ID FROM SECURITY WHERE NAME = 'Pinterest'), 35.36, 'USD', '2023-12-11', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ((SELECT ID FROM SECURITY WHERE NAME = 'Pinterest'), 36.13, 'USD', '2023-12-12', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ((SELECT ID FROM SECURITY WHERE NAME = 'Pinterest'), 36.51, 'USD', '2023-12-13', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ((SELECT ID FROM SECURITY WHERE NAME = 'Pinterest'), 34.11, 'USD', '2023-12-05', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ((SELECT ID FROM SECURITY WHERE NAME = 'Pinterest'), 37.01, 'USD', '2023-12-14', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ((SELECT ID FROM SECURITY WHERE NAME = 'Pinterest'), 37.37, 'USD', '2023-12-15', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ((SELECT ID FROM SECURITY WHERE NAME = 'Pinterest'), 37.7, 'USD', '2023-12-18', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ((SELECT ID FROM SECURITY WHERE NAME = 'Pinterest'), 38.04, 'USD', '2023-12-19', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ((SELECT ID FROM SECURITY WHERE NAME = 'Pinterest'), 37.12, 'USD', '2023-12-20', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ((SELECT ID FROM SECURITY WHERE NAME = 'Pinterest'), 37.36, 'USD', '2023-12-21', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ((SELECT ID FROM SECURITY WHERE NAME = 'Pinterest'), 37.38, 'USD', '2023-12-22', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ((SELECT ID FROM SECURITY WHERE NAME = 'Pinterest'), 37.16, 'USD', '2023-12-26', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ((SELECT ID FROM SECURITY WHERE NAME = 'Pinterest'), 37.3, 'USD', '2023-12-27', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ((SELECT ID FROM SECURITY WHERE NAME = 'Pinterest'), 37.27, 'USD', '2023-12-28', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ((SELECT ID FROM SECURITY WHERE NAME = 'Pinterest'), 37.04, 'USD', '2023-12-29', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Alphabet A
INSERT INTO HISTORICAL_SECURITY_PRICE (SECURITY_ID, PRICE, CURRENCY, DATE, CREATED_AT, UPDATED_AT)
VALUES ((SELECT ID FROM SECURITY WHERE NAME = 'Alphabet A'), 126.76, 'EUR', '2023-12-29', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Alphabet C
INSERT INTO HISTORICAL_SECURITY_PRICE (SECURITY_ID, PRICE, CURRENCY, DATE, CREATED_AT, UPDATED_AT)
VALUES ((SELECT ID FROM SECURITY WHERE NAME = 'Alphabet C'), 127.68, 'EUR', '2023-12-29', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Volkswagen VZ
INSERT INTO HISTORICAL_SECURITY_PRICE (SECURITY_ID, PRICE, CURRENCY, DATE, CREATED_AT, UPDATED_AT)
VALUES ((SELECT ID FROM SECURITY WHERE NAME = 'Volkswagen VZ'), 111.8, 'EUR', '2023-12-29', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Volkswagen Stamm
INSERT INTO HISTORICAL_SECURITY_PRICE (SECURITY_ID, PRICE, CURRENCY, DATE, CREATED_AT, UPDATED_AT)
VALUES ((SELECT ID FROM SECURITY WHERE NAME = 'Volkswagen Stamm'), 118.45, 'EUR', '2023-12-29', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
